### PR TITLE
read.me - add, update and correct some links

### PR DESCRIPTION
**Pull request by schwesig**
a) fix link to mailing list
current link still goes to [mailman](https://listman.redhat.com/mailman/listinfo/operate-first)
changed to [postorius](https://lists.operate-first.cloud/admin/lists/community.lists.operate-first.cloud/)

b) add new blog link

c) updated pull request process link

d) link thoth-application repository

### CODE REVIEW

**Comment by codificat** [comment]
I can't /approve in this repo, so @schwesig feel free to do so –although prow is having issues that might prevent merging until solved.

**Comment by schwesig** [comment]
/approve

@codificat give it a try..

**Review by quaid — APPROVED** [review]
Great catches, thanks

**Pull request merged**
