### PR TITLE
Add knikolla

### PR DESCRIPTION
**Pull request by schwesig**

### CODE REVIEW

**Comment by schwesig** [comment]
needs this https://github.com/operate-first/common/pull/154

**Review by schwesig — COMMENTED** [review]
/lgtm
/approve

**Comment by codificat** [comment]
> needs this [operate-first/common#154](https://github.com/operate-first/common/pull/154)

After merging that, an invite was sent to `knikolla` to join the org. He must accept that invitation, and then this can proceed

**Comment by codificat** [comment]
/hold
until @knikolla accepts the invitation to join the operate-first org

**Pull request closed without merging**
