### PR TITLE
update logo and favico

### PR DESCRIPTION
**Pull request by zafar-hussain**
closes #209

### CODE REVIEW

**Review by zafar-hussain — COMMENTED** [review]
update logo and favico 
closes #209

**Comment by zafar-hussain** [comment]
Hi @sesheta,

I am terribly sorry for jumping the gun, and should have asked first.

cheers

**Comment by zafar-hussain** [comment]
Hi @sesheta,

Any chance this PR can be merged before the end of October'22, i.e. by the end of Hacktoberfest

cheers

**Comment by schwesig** [comment]
Hi @zafar-hussain,
First of all: you did solve the problem, and your PR can close the issue https://github.com/operate-first/operate-first.github.io/issues/209
Great job!

And sorry from my side for not reacting in a timely correct manner. I apologize. It fell through the cracks. Our team was focused on the hacktober labels and the open issues around this. This PR here was by accident (?) linked to a wrong issue. Therefore I didn't connect it fast enough. That is on us.

One week after the end of hacktober, I started cleaning up and solving still open issues, then found yours.
In the meantime, the logos were already replaced by two other PRs, and we now have a merging conflict.

I would love to accept and use your PR.
To do this, and if you want this,
can you please rename the icon.png to logo.png in your PR? Then it will fit into the new _config.yml

**Comment by zafar-hussain** [comment]
Hi, @schwesig,

Thanks for the reply,

no worries, I will close this PR.

Cheers and keep well

**Pull request closed without merging**
