### PR TITLE
WIP add a subproject for airgapped operations of ODH

### PR DESCRIPTION
**Pull request by goern**
This is a proposed subproject to investigate how to deploy and operate ODH in airgapped environments, there has been some work on this topic, but it needs review and structure. The intention it to contribute back to ODH community and involve business partners too.

I think this depends on #130 therefor I have not regenerated any .md

Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Comment by HumairAK** [comment]
can we add this to the upcoming meeting agenda on tuesday and discuss it there? 

- https://docs.google.com/document/d/1uEcLGP_sBSNwTLPOo_2Nu6oTqPytOTBt0c0_pVUQJwo/edit

**Comment by HumairAK** [comment]
ignore netfliy errors as per: https://github.com/operate-first/community/pull/130#issuecomment-1036609710

**Comment by durandom** [comment]
similar discussion happening in the ODH slack https://odh-io.slack.com/archives/C033X6XM448/p1645639760366989

**Comment by durandom** [comment]
also check https://issues.redhat.com/browse/ODH-177

**Comment by HumairAK** [comment]
@durandom iirc from the last sig-ops meeting, you mentioned this does not fall under sig-ops yes?

**Comment by quaid** [comment]
@goern Since this doesn't seem to be part of the SIG Ops purpose, we can organize this through SIG Community.

It appears to me that a subproject is the correct group type — the group will be doing work and the work will be ongoing.

As we start building out the SRE/cloud operator community, a different SIG may come along that is a better fit for having oversight on this subproject.

I'm proposing a git workflow-based process for proposing new groups, I'll be trying to take this one (with some others) through that nascent process.

**Review by quaid — CHANGES_REQUESTED** [review]
This week let's make sure we talk about this proposal on the mailing list and Slack.

@goern Can you start a thread on the contrib@lists.operate-first.cloud mailing list, proposing this subproject, with a few sentences about its purpose/scope.

This doesn't seem like a fit for SIG Operations, as their purview is not looking for novel ways to hack software. SIG Ops is involved if e.g. you need a pseudo-gapped cluster for testing.

What do others think?

Ultimately I think this is a fit for a subproject under something like a SIG focused on OpenShift. It could fit under a data science SIG, if air-gapping ODH feels to those folx like its in their purview.

For now, I think you should create this in `sig-community/subprojects/`.

Either way, I'm sending this back for changes so you can solve the merge conflict.

**Comment by quaid** [comment]
ping @goern

**Pull request closed without merging**
