### PR TITLE
Added links to Slack and Operate First community calendar

### PR DESCRIPTION
**Pull request by bryanmontalvan**
## Description:
This PR adds links to our community page on how to be involved in meetings and discussions. 
- Slack link
- Google calendar link

### CODE REVIEW

**Review by oindrillac — APPROVED** [review]
/lgtm
/approve

**Comment by oindrillac** [comment]
@bryanmontalvan can you fix the trailing whitespace to fix the pre-commit?

**Comment by oindrillac** [comment]
cc: @HumairAK @quaid for /approvals

**Comment by quaid** [comment]
Good stuff, thanks. Looks like you have an edit to `open-source-services.md` as well, I keep having that happen to me. I wonder if we can better document the fork  > clone > branch > edit > commit > push process better, especially when working on a local fork vs the web UI.

/lgtm
/approve

**Pull request merged**
