### PR TITLE
Operate First Community Metrics EDA notebook

### PR DESCRIPTION
**Pull request by hemajv**
Initial notebook to fetch and visualize the GitHub metrics for the Operate First community.

Related Issues:
https://github.com/operate-first/community/issues/22
https://github.com/AICoE/data-driven-development/issues/4

### CODE REVIEW

**Comment by durandom** [comment]
@hemajv can we just keep the `alerts` repo out of the graphs?

**Comment by durandom** [comment]
and can you run the same notebook on the 2021-09-01 and have the graphs display just months until August?

**Review by quaid — COMMENTED** [review]
I don't know enough yet to comment on the  Jupyter notebook itself, but the overall approach and what is being looked at are great bits of first-order metrics to capture. I could maybe see putting some roadmap parts on here e.g. mailing list analysis, but we can add those later.
/lgtm
/approve

**Review by durandom — APPROVED** [review]
👏 great start. Thanks @hemajv @Shreyanand @cdolfi

**Pull request merged**
