### PR TITLE
Add Meeting notes link to sig operations 

### PR DESCRIPTION
**Pull request by rbo**
As discussed in our meeting today.

### CODE REVIEW

**Comment by rbo** [comment]
```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: remote error: 
      The unauthenticated git protocol on port 9418 is no longer supported.
    Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    
Check the log at /opt/app-root/src/.cache/pre-commit/pre-commit.log
```
Looks strange....

Locally everything is fine:
```
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
Fix End of Files.........................................................Passed
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
yamllint.................................................................Passed
$
```

/retest

**Review by Gregory-Pereira — CHANGES_REQUESTED** [review]
change these two lines in the `.pre-commit-config.yaml`:
1. [Line 3](https://github.com/operate-first/community/blob/main/.pre-commit-config.yaml#L3) should be `- repo: https://github.com/Lucas-C/pre-commit-hooks`
2. [Line 8](https://github.com/operate-first/community/blob/main/.pre-commit-config.yaml#L8) should be `- repo: https://github.com/pre-commit/pre-commit-hooks`

**Comment by Gregory-Pereira** [comment]
Pr is out.
Depends on: https://github.com/operate-first/community/pull/152

**Comment by HumairAK** [comment]
gotta add it here: https://github.com/operate-first/community/blob/main/sigs.yaml#L70 

Then generate the readme file by running: 

```
podman run --rm --volume $(pwd):/workdir:Z quay.io/open-services-group/community-tooling:v0.1.0-dev
```

**Comment by quaid** [comment]
While this is currently accurate, I am proposing in #158 that we have a subfolder for each subproject, WG, and SIG for `meeting-notes` with one .md file per meeting. Then we can use any shareable text editor to collaborate on the source before it's put into the template, but this process is particularly conducive to the HackMD.io-type solutions.

**Comment by quaid** [comment]
> /approved

*sigh*

**Pull request merged**
