### PR TITLE
Clean-up and addition of how-to-naming details

### PR DESCRIPTION
**Pull request by quaid**
Lots of cruft and old discussion material removed.

Reformatted for easier reading and maintaining.

Updated content e.g. for NERC, MOC Alliance, etc.

### CODE REVIEW

**Review by schwesig — APPROVED** [review]
/lgtm
/approve

**Comment by schwesig** [comment]
@quaid thanks for the "spring cleaning" 👍

**Comment by quaid** [comment]
There was a nasty trailing whitespace and a link to my blog for some reason, removed and should work, so let's ...
/retest

**Comment by quaid** [comment]
With the merge of #229 this one should work, so I'm queueing it up for...
/retest

**Pull request merged**
